### ISSUE TITLE
Determine Lowest Necessary WP Version

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/plugin-state-switcher#1]
If the site is < WP 4.6 it returns an error. Although things appear to be working fine on a local instance where I'm running 4.4.5 with that check commented out.

Is there some functionality that is only in 4.6 that the plugin needs? It seemed to have some difficulty saving its first State, but after that there've been no issues. I'm thinking that that could have been caused by an active plugin throwing PHP errors and breaking the AJAX though.

**Comment by joelworsham** [comment]
Hmmm I just like to require newer versions with more development projects. I set that before even breaking ground on the plugin. I would be fine figuring out the truly lowest possible version of WP supported and use that, but there's definitely no need to lower than... say... 4.0.0. I want to future proof the ability to use latest WP functionality in projects, when possible.

**Comment by d4mation** [comment]
Ok, that's what I was thinking it was, but I wasn't sure. 

Supporting newer versions is definitely better, but in this case the client's site is on an ancient version so I needed to also run that same version, haha.

**Comment by joelworsham** [comment]
Well, let's do 2 two things:

1. Figure out the truly lowest version required, and then figure out an appropriate compromise
2. Make that value filterable, for edge-case, lower version websites. A supplementary plugin can modify that version. Well, rather than filter the number, filter the "mode". Use that compromise mentioned above, but allow a mode that uses the lowest possible version required, that way it can't break.

**Comment by d4mation** [comment]
Did you pick the minimum PHP version requirement similarly? Just ran into an issue on a Live install where I was going to use it to quickly toggle some plugins and they were running PHP 5.5.9.

**Comment by joelworsham** [comment]
Yeaaaaahhh :X

**Comment by joelworsham** [comment]
Just pushed a patch. You can now filter `pluginss_dependencies_version_mode` to be `minimum` instead of `recommended`

**Comment by d4mation** [comment]
Nice 👍 That's a pretty neat way to handle it.

**Comment by joelworsham** [comment]
Probably wouldn't handle it that way on a more public plugin, but for something like this, meh, why not

**Comment by d4mation** [comment]
Agreed. Definitely not a good way for public plugins, but it fits what we need here.
